Fix a TypeError that occur when invoking render_plot()
If |visualize| is True, biwi_evaluation.ipynb breaks at:

         59
         60         if visualize and best_index >= 0:
    ---> 61             render_plot(ori_img.copy(), pose_pred, bbox)
         62
         63     if len(poses) == 0:
    TypeError: render_plot() takes 2 positional arguments but 3 were given